changelog:
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Dependencies & other changes
      labels:
        - "*"
