[tool.poetry]
name = "test-runners-data-platform"
version = "0.2.0"
description = ""
authors = ["Alex Batisse <alex.batisse@canonical.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
