on:
  pull_request:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/canonical/charmed-postgresql:14.13-22.04_edge@sha256:3f894e1be0570d2ef6541ca1c0a27dd4cca4cb19840d36f4d82c89e4c964ca36
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
