on:
  push:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install git+https://github.com/canonical/jhack@optimize-tail
      - run: jhack tail --file juju-debug-log.txt --replay --length=50000 --no-watch --printer raw
      - run: jhack tail --file juju-debug-log.txt --replay --length=50000 --no-watch
