name: Push

on:
  push:
    branches:
      - main
      - stable/2023.1
      - stable/2023.2
      - stable/2024.1

jobs:
  build-and-publish:
    uses: ./.github/workflows/build_publish.yaml
    with:
      rocks: ${{ toJSON(['neutron-server']) }}
      publish: true
      branch: ${{ github.ref }}
