# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release PG-VM to Charmhub (Lucas Test)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@lucas/test-charmcraft-3

  release:
    name: Release charm
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@lucas/test-charmcraft-3
    with:
      channel: latest/stable
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      charmcraft-snap-channel: 3.x/candidate
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN_VM }}
    permissions:
      contents: write  # Needed to create GitHub release
